import { Doctor, Specialty, Product, Visit, Target, GeoCoordinates, User } from '@/types';

// Specialties
export const MOCK_SPECIALTIES: Specialty[] = [
  { id: 'spec-1', name: 'Cardiology', companyId: 'comp-1' },
  { id: 'spec-2', name: 'Neurology', companyId: 'comp-1' },
  { id: 'spec-3', name: 'Endocrinology', companyId: 'comp-1' },
  { id: 'spec-4', name: 'Pulmonology', companyId: 'comp-1' },
  { id: 'spec-5', name: 'Gastroenterology', companyId: 'comp-1' },
  { id: 'spec-6', name: 'Psychiatry', companyId: 'comp-1' },
  { id: 'spec-7', name: 'Oncology', companyId: 'comp-1' },
  { id: 'spec-8', name: 'Rheumatology', companyId: 'comp-1' },
];

export const MOCK_REPS: User[] = [
  {
    id: '3',
    email: 'rep1@pharmacorp.com',
    name: 'Emily Chen',
    phone: '+1-415-555-1003',
    employeeId: 'REP-003',
    role: 'MEDICAL_REP',
    profileImage: '',
    jobTitle: 'Medical Representative',
    isActive: true,
    companyId: 'comp-1',
    managerId: '2',
    workingDays: [1, 2, 3, 4, 5],
    workingHours: { start: '09:00', end: '17:00' },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '4',
    email: 'rep2@pharmacorp.com',
    name: 'Michael Thompson',
    phone: '+1-415-555-1004',
    employeeId: 'REP-004',
    role: 'MEDICAL_REP',
    profileImage: '',
    jobTitle: 'Medical Representative',
    isActive: true,
    companyId: 'comp-1',
    managerId: '2',
    workingDays: [1, 2, 3, 4, 5],
    workingHours: { start: '09:00', end: '17:00' },
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
];

// Doctors in San Francisco Bay Area (for testing geolocation)
export const MOCK_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Robert Anderson',
    phone: '+1-415-555-0101',
    email: 'r.anderson@sfcardiology.com',
    specialtyId: 'spec-1',
    subSpecialty: 'Interventional Cardiology',
    gender: 'Male',
    clinicName: 'San Francisco Heart Institute',
    address: '1100 Van Ness Ave, San Francisco, CA 94109',
    governorate: 'San Francisco',
    city: 'San Francisco',
    latitude: 37.7879,
    longitude: -122.4214,
    priority: 'A',
    companyId: 'comp-1',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    specialty: MOCK_SPECIALTIES[0],
  },
  {
    id: 'doc-2',
    name: 'Dr. Lisa Martinez',
    phone: '+1-415-555-0102',
    email: 'l.martinez@neurology-sf.com',
    specialtyId: 'spec-2',
    subSpecialty: 'Stroke Neurology',
    gender: 'Female',
    clinicName: 'UCSF Neurology Clinic',
    address: '400 Parnassus Ave, San Francisco, CA 94143',
    governorate: 'San Francisco',
    city: 'San Francisco',
    latitude: 37.7632,
    longitude: -122.4585,
    priority: 'A',
    companyId: 'comp-1',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    specialty: MOCK_SPECIALTIES[1],
  },
  {
    id: 'doc-3',
    name: 'Dr. James Wilson',
    phone: '+1-415-555-0103',
    email: 'j.wilson@endocrine-sf.com',
    specialtyId: 'spec-3',
    subSpecialty: 'Diabetes & Metabolism',
    gender: 'Male',
    clinicName: 'California Diabetes Center',
    address: '2100 Webster St, San Francisco, CA 94115',
    governorate: 'San Francisco',
    city: 'San Francisco',
    latitude: 37.7916,
    longitude: -122.4312,
    priority: 'B',
    companyId: 'comp-1',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
    specialty: MOCK_SPECIALTIES[2],
  },
  {
    id: 'doc-4',
    name: 'Dr. Sarah Kim',
    phone: '+1-650-555-0104',
    email: 's.kim@pulmo-paloalto.com',
    specialtyId: 'spec-4',
    subSpecialty: 'Sleep Medicine',
    gender: 'Female',
    clinicName: 'Palo Alto Pulmonary Associates',
    address: '875 Blake Wilbur Dr, Palo Alto, CA 94304',
    governorate: 'Santa Clara',
    city: 'Palo Alto',
    latitude: 37.4312,
    longitude: -122.1598,
    priority: 'B',
    companyId: 'comp-1',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
    specialty: MOCK_SPECIALTIES[3],
  },
  {
    id: 'doc-5',
    name: 'Dr. David Chen',
    phone: '+1-650-555-0105',
    email: 'd.chen@gi-mountainview.com',
    specialtyId: 'spec-5',
    subSpecialty: 'Inflammatory Bowel Disease',
    gender: 'Male',
    clinicName: 'Mountain View Gastroenterology',
    address: '2495 Hospital Dr, Mountain View, CA 94040',
    governorate: 'Santa Clara',
    city: 'Mountain View',
    latitude: 37.4085,
    longitude: -122.0775,
    priority: 'C',
    companyId: 'comp-1',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
    specialty: MOCK_SPECIALTIES[4],
  },
  {
    id: 'doc-6',
    name: 'Dr. Jennifer Lopez',
    phone: '+1-510-555-0106',
    email: 'j.lopez@psych-oakland.com',
    specialtyId: 'spec-6',
    subSpecialty: 'Adult Psychiatry',
    gender: 'Female',
    clinicName: 'Oakland Mental Health Center',
    address: '3100 Summit St, Oakland, CA 94609',
    governorate: 'Alameda',
    city: 'Oakland',
    latitude: 37.8184,
    longitude: -122.2572,
    priority: 'B',
    companyId: 'comp-1',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
    specialty: MOCK_SPECIALTIES[5],
  },
  {
    id: 'doc-7',
    name: 'Dr. William Brown',
    phone: '+1-415-555-0107',
    email: 'w.brown@onco-ucsf.com',
    specialtyId: 'spec-7',
    subSpecialty: 'Breast Oncology',
    gender: 'Male',
    clinicName: 'UCSF Helen Diller Cancer Center',
    address: '1600 Divisadero St, San Francisco, CA 94143',
    governorate: 'San Francisco',
    city: 'San Francisco',
    latitude: 37.7819,
    longitude: -122.4456,
    priority: 'A',
    companyId: 'comp-1',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
    specialty: MOCK_SPECIALTIES[6],
  },
  {
    id: 'doc-8',
    name: 'Dr. Amanda Foster',
    phone: '+1-415-555-0108',
    email: 'a.foster@rheum-sf.com',
    specialtyId: 'spec-8',
    subSpecialty: 'Rheumatoid Arthritis',
    gender: 'Female',
    clinicName: 'San Francisco Rheumatology',
    address: '2340 Clay St, San Francisco, CA 94115',
    governorate: 'San Francisco',
    city: 'San Francisco',
    latitude: 37.7942,
    longitude: -122.4287,
    priority: 'C',
    companyId: 'comp-1',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
    specialty: MOCK_SPECIALTIES[7],
  },
  {
    id: 'doc-9',
    name: 'Dr. Christopher Lee',
    phone: '+1-650-555-0109',
    email: 'c.lee@cardio-redwood.com',
    specialtyId: 'spec-1',
    subSpecialty: 'Heart Failure',
    gender: 'Male',
    clinicName: 'Redwood City Cardiology',
    address: '1100 Veterans Blvd, Redwood City, CA 94063',
    governorate: 'San Mateo',
    city: 'Redwood City',
    latitude: 37.4852,
    longitude: -122.2364,
    priority: 'B',
    companyId: 'comp-1',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
    specialty: MOCK_SPECIALTIES[0],
  },
  {
    id: 'doc-10',
    name: 'Dr. Michelle Taylor',
    phone: '+1-408-555-0110',
    email: 'm.taylor@neuro-sanjose.com',
    specialtyId: 'spec-2',
    subSpecialty: 'Movement Disorders',
    gender: 'Female',
    clinicName: 'San Jose Neurology Group',
    address: '25 N 14th St, San Jose, CA 95112',
    governorate: 'Santa Clara',
    city: 'San Jose',
    latitude: 37.3382,
    longitude: -121.8863,
    priority: 'C',
    companyId: 'comp-1',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
    specialty: MOCK_SPECIALTIES[1],
  },
];

// Products
export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-1',
    name: 'CardioVance',
    genericName: 'Apixaban',
    category: 'Anticoagulant',
    description: 'Oral Factor Xa inhibitor for stroke prevention in atrial fibrillation',
    dosageInfo: '5mg twice daily, 2.5mg twice daily for selected patients',
    companyId: 'comp-1',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'prod-2',
    name: 'NeuroShield',
    genericName: 'Ocrelizumab',
    category: 'Multiple Sclerosis',
    description: 'Anti-CD20 monoclonal antibody for relapsing and primary progressive MS',
    dosageInfo: '600mg IV infusion every 6 months',
    companyId: 'comp-1',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'prod-3',
    name: 'GlucoControl XR',
    genericName: 'Dulaglutide',
    category: 'Diabetes',
    description: 'Once-weekly GLP-1 receptor agonist for type 2 diabetes',
    dosageInfo: '0.75mg, 1.5mg, 3mg, or 4.5mg once weekly SC',
    companyId: 'comp-1',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'prod-4',
    name: 'BreatheEasy',
    genericName: 'Tezepelumab',
    category: 'Respiratory',
    description: 'Anti-TSLP monoclonal antibody for severe asthma',
    dosageInfo: '210mg SC every 4 weeks',
    companyId: 'comp-1',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'prod-5',
    name: 'GastroCalm',
    genericName: 'Ustekinumab',
    category: 'Gastroenterology',
    description: 'IL-12/23 inhibitor for Crohn\'s disease and ulcerative colitis',
    dosageInfo: 'Weight-based IV induction, then 90mg SC every 8 weeks',
    companyId: 'comp-1',
    isActive: true,
    createdAt: new Date('2024-01-01'),
  },
];

// Mock visits for testing
export const MOCK_VISITS: Visit[] = [
  {
    id: 'visit-1',
    repId: '3',
    doctorId: 'doc-1',
    visitPurpose: 'DETAILING',
    status: 'COMPLETED',
    startTime: new Date('2024-12-15T09:00:00'),
    endTime: new Date('2024-12-15T09:45:00'),
    duration: 45,
    latitude: 37.7879,
    longitude: -122.4214,
    distanceFromDoctor: 15,
    isVerified: true,
    doctorResponse: 'INTERESTED',
    notes: 'Discussed CardioVance for AF patients. Dr. Anderson interested in clinical data.',
    nextFollowUpDate: new Date('2025-01-15'),
    nextFollowUpType: 'VISIT',
    nextFollowUpNotes: 'Follow up on CardioVance adoption',
    companyId: 'comp-1',
    createdAt: new Date('2024-12-15'),
  },
  {
    id: 'visit-2',
    repId: '3',
    doctorId: 'doc-3',
    visitPurpose: 'FOLLOW_UP',
    status: 'COMPLETED',
    startTime: new Date('2024-12-14T10:30:00'),
    endTime: new Date('2024-12-14T11:00:00'),
    duration: 30,
    latitude: 37.7916,
    longitude: -122.4312,
    distanceFromDoctor: 25,
    isVerified: true,
    doctorResponse: 'VERY_INTERESTED',
    notes: 'Follow up on GlucoControl XR. Dr. Wilson started 3 patients.',
    nextFollowUpDate: new Date('2025-01-14'),
    nextFollowUpType: 'CALL',
    nextFollowUpNotes: 'Check patient outcomes',
    companyId: 'comp-1',
    createdAt: new Date('2024-12-14'),
  },
  {
    id: 'visit-3',
    repId: '4',
    doctorId: 'doc-4',
    visitPurpose: 'PRODUCT_LAUNCH',
    status: 'COMPLETED',
    startTime: new Date('2024-12-13T14:00:00'),
    endTime: new Date('2024-12-13T14:50:00'),
    duration: 50,
    latitude: 37.4312,
    longitude: -122.1598,
    distanceFromDoctor: 10,
    isVerified: true,
    doctorResponse: 'INTERESTED',
    notes: 'Launched BreatheEasy for severe asthma. Dr. Kim requested samples.',
    nextFollowUpDate: new Date('2025-01-13'),
    nextFollowUpType: 'VISIT',
    nextFollowUpNotes: 'Deliver samples and discuss patient selection',
    companyId: 'comp-1',
    createdAt: new Date('2024-12-13'),
  },
];

// Mock targets
export const MOCK_TARGETS: Target[] = [
  {
    id: 'target-1',
    repId: '3',
    month: 12,
    year: 2024,
    totalVisits: 20,
    totalDoctors: 15,
    newDoctors: 3,
    followUps: 10,
    companyId: 'comp-1',
    createdAt: new Date('2024-12-01'),
  },
  {
    id: 'target-2',
    repId: '4',
    month: 12,
    year: 2024,
    totalVisits: 20,
    totalDoctors: 15,
    newDoctors: 3,
    followUps: 10,
    companyId: 'comp-1',
    createdAt: new Date('2024-12-01'),
  },
];

// Default location for testing (San Francisco downtown)
export const DEFAULT_REP_LOCATION: GeoCoordinates = {
  latitude: 37.7749,
  longitude: -122.4194,
};

// Priority color mapping
export const PRIORITY_COLORS: Record<string, string> = {
  A: 'bg-red-100 text-red-800 border-red-200',
  B: 'bg-yellow-100 text-yellow-800 border-yellow-200',
  C: 'bg-green-100 text-green-800 border-green-200',
};

export const PRIORITY_LABELS: Record<string, string> = {
  A: 'High Priority',
  B: 'Medium Priority',
  C: 'Low Priority',
};

export const VISIT_PURPOSE_LABELS: Record<string, string> = {
  DETAILING: 'Detailing',
  FOLLOW_UP: 'Follow-up',
  PRODUCT_LAUNCH: 'Product Launch',
  SAMPLE_DELIVERY: 'Sample Delivery',
  MEDICAL_EDUCATION: 'Medical Education',
  RELATIONSHIP_BUILDING: 'Relationship Building',
};

export const DOCTOR_RESPONSE_LABELS: Record<string, string> = {
  VERY_INTERESTED: 'Very Interested',
  INTERESTED: 'Interested',
  NEUTRAL: 'Neutral',
  NOT_INTERESTED: 'Not Interested',
};

export const VISIT_STATUS_LABELS: Record<string, string> = {
  IN_PROGRESS: 'In Progress',
  COMPLETED: 'Completed',
  CANCELLED: 'Cancelled',
};

export const VISIT_STATUS_COLORS: Record<string, string> = {
  IN_PROGRESS: 'bg-blue-100 text-blue-800',
  COMPLETED: 'bg-green-100 text-green-800',
  CANCELLED: 'bg-red-100 text-red-800',
};