"""add is_super_admin to users

Revision ID: 56cfeff47b4c
Revises: d0f54c9b6f26
Create Date: 2026-09-16 17:53:12.847092

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56cfeff47b4c'
down_revision: Union[str, None] = 'd0f54c9b6f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_index(op.f('ix_users_is_super_admin'), 'users', ['is_super_admin'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_is_super_admin'), table_name='users')
    op.drop_column('users', 'is_super_admin')
    # ### end Alembic commands ###