"""add sales table and product pricing

Revision ID: 5eef593d111f
Revises: 56cfeff47b4c
Create Date: 2026-09-16 23:24:11.371618

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eef593d111f'
down_revision: Union[str, None] = '56cfeff47b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('rep_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'DELIVERED', 'CANCELLED', name='salestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rep_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_doctor', 'sales', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_sales_doctor_id'), 'sales', ['doctor_id'], unique=False)
    op.create_index('ix_sales_org', 'sales', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sales_organization_id'), 'sales', ['organization_id'], unique=False)
    op.create_index('ix_sales_product', 'sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_sales_product_id'), 'sales', ['product_id'], unique=False)
    op.create_index('ix_sales_rep', 'sales', ['rep_id'], unique=False)
    op.create_index(op.f('ix_sales_rep_id'), 'sales', ['rep_id'], unique=False)
    op.create_index(op.f('ix_sales_sold_at'), 'sales', ['sold_at'], unique=False)
    op.create_index(op.f('ix_sales_status'), 'sales', ['status'], unique=False)
    op.create_index(op.f('ix_sales_visit_id'), 'sales', ['visit_id'], unique=False)
    op.add_column('products', sa.Column('unit_price', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('unit_cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'unit_cost')
    op.drop_column('products', 'unit_price')
    op.drop_index(op.f('ix_sales_visit_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_status'), table_name='sales')
    op.drop_index(op.f('ix_sales_sold_at'), table_name='sales')
    op.drop_index(op.f('ix_sales_rep_id'), table_name='sales')
    op.drop_index('ix_sales_rep', table_name='sales')
    op.drop_index(op.f('ix_sales_product_id'), table_name='sales')
    op.drop_index('ix_sales_product', table_name='sales')
    op.drop_index(op.f('ix_sales_organization_id'), table_name='sales')
    op.drop_index('ix_sales_org', table_name='sales')
    op.drop_index(op.f('ix_sales_doctor_id'), table_name='sales')
    op.drop_index('ix_sales_doctor', table_name='sales')
    op.drop_table('sales')
    # ### end Alembic commands ###