"""add visits products targets notifications subscriptions

Revision ID: b6ef3be267cb
Revises: f0cbe8702067
Create Date: 2026-09-15 20:07:47.778372

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'b6ef3be267cb'
down_revision: Union[str, None] = 'f0cbe8702067'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_specialties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doctor_specialties_organization', 'doctor_specialties', ['organization_id'], unique=False)
    op.create_index(op.f('ix_doctor_specialties_organization_id'), 'doctor_specialties', ['organization_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('generic_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dosage_info', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_organization', 'products', ['organization_id'], unique=False)
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.Enum('BASIC', 'PROFESSIONAL', 'ENTERPRISE', name='subscriptionplan'), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_index('ix_subscriptions_organization', 'subscriptions', ['organization_id'], unique=False)
    op.create_table('doctor_locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doctor_locations_doctor', 'doctor_locations', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_locations_doctor_id'), 'doctor_locations', ['doctor_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('VISIT', 'FOLLOW_UP', 'TARGET', 'SYSTEM', 'ASSIGNMENT', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_user', 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('targets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rep_id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_visits', sa.Integer(), nullable=False),
    sa.Column('total_doctors', sa.Integer(), nullable=False),
    sa.Column('new_doctors', sa.Integer(), nullable=False),
    sa.Column('follow_ups', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rep_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rep_id', 'month', 'year', name='uq_rep_month_year')
    )
    op.create_index('ix_targets_organization', 'targets', ['organization_id'], unique=False)
    op.create_index(op.f('ix_targets_organization_id'), 'targets', ['organization_id'], unique=False)
    op.create_index('ix_targets_rep', 'targets', ['rep_id'], unique=False)
    op.create_index(op.f('ix_targets_rep_id'), 'targets', ['rep_id'], unique=False)
    op.create_table('doctor_schedules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_location_id', sa.String(length=36), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_location_id'], ['doctor_locations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doctor_schedules_doctor', 'doctor_schedules', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_schedules_doctor_id'), 'doctor_schedules', ['doctor_id'], unique=False)
    op.create_table('visits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rep_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_location_id', sa.String(length=36), nullable=True),
    sa.Column('visit_purpose', sa.Enum('DETAILING', 'FOLLOW_UP', 'PRODUCT_LAUNCH', 'SAMPLE_DELIVERY', 'MEDICAL_EDUCATION', 'RELATIONSHIP_BUILDING', name='visitpurpose'), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'CHECKED_IN', 'COMPLETED', 'MISSED', 'CANCELLED', name='visitstatus'), nullable=False),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('checkin_latitude', sa.Float(), nullable=True),
    sa.Column('checkin_longitude', sa.Float(), nullable=True),
    sa.Column('checkout_latitude', sa.Float(), nullable=True),
    sa.Column('checkout_longitude', sa.Float(), nullable=True),
    sa.Column('distance_from_doctor', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('doctor_response', sa.Enum('VERY_INTERESTED', 'INTERESTED', 'NEUTRAL', 'NOT_INTERESTED', name='doctorresponse'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_follow_up_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_follow_up_type', sa.String(length=100), nullable=True),
    sa.Column('next_follow_up_notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_location_id'], ['doctor_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rep_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visits_created_at', 'visits', ['created_at'], unique=False)
    op.create_index('ix_visits_doctor', 'visits', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_visits_doctor_id'), 'visits', ['doctor_id'], unique=False)
    op.create_index('ix_visits_organization', 'visits', ['organization_id'], unique=False)
    op.create_index(op.f('ix_visits_organization_id'), 'visits', ['organization_id'], unique=False)
    op.create_index('ix_visits_rep', 'visits', ['rep_id'], unique=False)
    op.create_index(op.f('ix_visits_rep_id'), 'visits', ['rep_id'], unique=False)
    op.create_index('ix_visits_status', 'visits', ['status'], unique=False)
    op.create_table('follow_ups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rep_id', sa.String(length=36), nullable=False),
    sa.Column('doctor_id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action_type', sa.Enum('CALL', 'VISIT', 'SEND_INFO', 'OTHER', name='followupactiontype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'OVERDUE', 'CANCELLED', name='followupstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rep_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_follow_ups_doctor', 'follow_ups', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_doctor_id'), 'follow_ups', ['doctor_id'], unique=False)
    op.create_index('ix_follow_ups_due_date', 'follow_ups', ['due_date'], unique=False)
    op.create_index('ix_follow_ups_organization', 'follow_ups', ['organization_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_organization_id'), 'follow_ups', ['organization_id'], unique=False)
    op.create_index('ix_follow_ups_rep', 'follow_ups', ['rep_id'], unique=False)
    op.create_index(op.f('ix_follow_ups_rep_id'), 'follow_ups', ['rep_id'], unique=False)
    op.create_index('ix_follow_ups_status', 'follow_ups', ['status'], unique=False)
    op.create_table('visit_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('visit_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('visit_id', 'product_id', name='uq_visit_product')
    )
    op.create_index('ix_visit_products_product', 'visit_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_visit_products_product_id'), 'visit_products', ['product_id'], unique=False)
    op.create_index('ix_visit_products_visit', 'visit_products', ['visit_id'], unique=False)
    op.create_index(op.f('ix_visit_products_visit_id'), 'visit_products', ['visit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visit_products_visit_id'), table_name='visit_products')
    op.drop_index('ix_visit_products_visit', table_name='visit_products')
    op.drop_index(op.f('ix_visit_products_product_id'), table_name='visit_products')
    op.drop_index('ix_visit_products_product', table_name='visit_products')
    op.drop_table('visit_products')
    op.drop_index('ix_follow_ups_status', table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_rep_id'), table_name='follow_ups')
    op.drop_index('ix_follow_ups_rep', table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_organization_id'), table_name='follow_ups')
    op.drop_index('ix_follow_ups_organization', table_name='follow_ups')
    op.drop_index('ix_follow_ups_due_date', table_name='follow_ups')
    op.drop_index(op.f('ix_follow_ups_doctor_id'), table_name='follow_ups')
    op.drop_index('ix_follow_ups_doctor', table_name='follow_ups')
    op.drop_table('follow_ups')
    op.drop_index('ix_visits_status', table_name='visits')
    op.drop_index(op.f('ix_visits_rep_id'), table_name='visits')
    op.drop_index('ix_visits_rep', table_name='visits')
    op.drop_index(op.f('ix_visits_organization_id'), table_name='visits')
    op.drop_index('ix_visits_organization', table_name='visits')
    op.drop_index(op.f('ix_visits_doctor_id'), table_name='visits')
    op.drop_index('ix_visits_doctor', table_name='visits')
    op.drop_index('ix_visits_created_at', table_name='visits')
    op.drop_table('visits')
    op.drop_index(op.f('ix_doctor_schedules_doctor_id'), table_name='doctor_schedules')
    op.drop_index('ix_doctor_schedules_doctor', table_name='doctor_schedules')
    op.drop_table('doctor_schedules')
    op.drop_index(op.f('ix_targets_rep_id'), table_name='targets')
    op.drop_index('ix_targets_rep', table_name='targets')
    op.drop_index(op.f('ix_targets_organization_id'), table_name='targets')
    op.drop_index('ix_targets_organization', table_name='targets')
    op.drop_table('targets')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index('ix_notifications_user', table_name='notifications')
    op.drop_index('ix_notifications_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_doctor_locations_doctor_id'), table_name='doctor_locations')
    op.drop_index('ix_doctor_locations_doctor', table_name='doctor_locations')
    op.drop_table('doctor_locations')
    op.drop_index('ix_subscriptions_organization', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_index('ix_products_organization', table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_doctor_specialties_organization_id'), table_name='doctor_specialties')
    op.drop_index('ix_doctor_specialties_organization', table_name='doctor_specialties')
    op.drop_table('doctor_specialties')
    # ### end Alembic commands ###