"""add doctor area column

Revision ID: d0f54c9b6f26
Revises: b6ef3be267cb
Create Date: 2026-09-15 21:18:53.800443

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0f54c9b6f26'
down_revision: Union[str, None] = 'b6ef3be267cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('area', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_doctors_area'), 'doctors', ['area'], unique=False)
    op.add_column('products', sa.Column('owner_user_id', sa.String(length=36), nullable=False))
    op.add_column('products', sa.Column('assigned_to_user_id', sa.String(length=36), nullable=True))
    op.add_column('products', sa.Column('visible_to_all', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_products_assigned', 'products', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_products_assigned_to_user_id'), 'products', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index('ix_products_owner', 'products', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_products_owner_user_id'), 'products', ['owner_user_id'], unique=False)
    op.create_index(op.f('ix_products_visible_to_all'), 'products', ['visible_to_all'], unique=False)
    op.create_foreign_key('fk_products_assigned_to_user', 'products', 'users', ['assigned_to_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_products_owner_user', 'products', 'users', ['owner_user_id'], ['id'], ondelete='CASCADE')
    op.add_column('visits', sa.Column('feedback_positive', sa.Text(), nullable=True))
    op.add_column('visits', sa.Column('feedback_objections', sa.Text(), nullable=True))
    op.add_column('visits', sa.Column('feedback_next_steps', sa.Text(), nullable=True))
    op.add_column('visits', sa.Column('feedback_overall', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visits', 'feedback_overall')
    op.drop_column('visits', 'feedback_next_steps')
    op.drop_column('visits', 'feedback_objections')
    op.drop_column('visits', 'feedback_positive')
    op.drop_constraint('fk_products_owner_user', 'products', type_='foreignkey')
    op.drop_constraint('fk_products_assigned_to_user', 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_visible_to_all'), table_name='products')
    op.drop_index(op.f('ix_products_owner_user_id'), table_name='products')
    op.drop_index('ix_products_owner', table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_products_assigned_to_user_id'), table_name='products')
    op.drop_index('ix_products_assigned', table_name='products')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'visible_to_all')
    op.drop_column('products', 'assigned_to_user_id')
    op.drop_column('products', 'owner_user_id')
    op.drop_index(op.f('ix_doctors_area'), table_name='doctors')
    op.drop_column('doctors', 'area')
    # ### end Alembic commands ###